var fonts = [];

function listFonts() {
alert('Hi');
	/* if it's IE get all the fonts */
	var nFontLen = dlgHelper.fonts.count;
        var rgFonts = new Array();
        for ( var i = 1; i < nFontLen + 1; i++ )
            rgFonts[i] = dlgHelper.fonts(i); 

        rgFonts.sort();
        for ( var j = 0; j < nFontLen; j++ )
		fonts.push(rgFonts[j]);


	var p = document.getElementById("panel");
	for(var i = 0; i < fonts.length; i++) {
		p.innerHTML += "<div style='class='1'; font-family: " + fonts[i] + ";'> b &nbsp; &nbsp; &nbsp; &nbsp; d</div>";
	}
}

/* When you have no IE un comment this 
var fonts[] = {
Agency FB,
Aharoni,
Algerian,
Andalus,
Angsana New,
AngsanaUPC,
Aparajita,
Arabic Typesetting,
Arial,
Arial Black,
Arial Narrow,
Arial Rounded MT Bold,
Arial Unicode MS,
Baskerville Old Face,
Batang,
BatangChe,
Bauhaus 93,
Bell MT,
Berlin Sans FB,
Berlin Sans FB Demi,
Bernard MT Condensed,
Blackadder ITC,
Bodoni MT,
Bodoni MT Black,
Bodoni MT Condensed,
Bodoni MT Poster Compressed,
Book Antiqua,
Bookman Old Style,
Bookshelf Symbol 7,
Bradley Hand ITC,
Britannic Bold,
Broadway,
Browallia New,
BrowalliaUPC,
Brush Script MT,
Calibri,
Californian FB,
Calisto MT,
Cambria,
Cambria Math,
Candara,
Castellar,
Centaur,
Century,
Century Gothic,
Century Schoolbook,
Chiller,
Colonna MT,
Comic Sans MS,
Consolas,
Constantia,
Cooper Black,
Copperplate Gothic Bold,
Copperplate Gothic Light,
Corbel,
Cordia New,
CordiaUPC,
Courier,
Courier New,
Curlz MT,
DFKai-SB,
DaunPenh,
David,
DilleniaUPC,
DokChampa,
Dotum,
DotumChe,
Ebrima,
Edwardian Script ITC,
Elephant,
Engravers MT,
Eras Bold ITC,
Eras Demi ITC,
Eras Light ITC,
Eras Medium ITC,
Estrangelo Edessa,
EucrosiaUPC,
Euphemia,
FangSong,
Felix Titling,
Fixedsys,
Footlight MT Light,
Forte,
FrankRuehl,
Franklin Gothic Book,
Franklin Gothic Demi,
Franklin Gothic Demi Cond,
Franklin Gothic Heavy,
Franklin Gothic Medium,
Franklin Gothic Medium Cond,
FreesiaUPC,
Freestyle Script,
French Script MT,
Gabriola,
Garamond,
Gautami,
Georgia,
Gigi,
Gill Sans MT,
Gill Sans MT Condensed,
Gill Sans MT Ext Condensed Bold,
Gill Sans Ultra Bold,
Gill Sans Ultra Bold Condensed,
Gisha,
Gloucester MT Extra Condensed,
Goudy Old Style,
Goudy Stout,
Gulim,
GulimChe,
Gungsuh,
GungsuhChe,
Haettenschweiler,
Harlow Solid Italic,
Harrington,
High Tower Text,
Impact,
Imprint MT Shadow,
Informal Roman,
IrisUPC,
Iskoola Pota,
JasmineUPC,
Jokerman,
Juice ITC,
KaiTi,
Kalinga,
Kartika,
Khmer UI,
KodchiangUPC,
Kokila,
Kristen ITC,
Kunstler Script,
Lao UI,
Latha,
Leelawadee,
Levenim MT,
LilyUPC,
Lucida Bright,
Lucida Calligraphy,
Lucida Console,
Lucida Fax,
Lucida Handwriting,
Lucida Sans,
Lucida Sans Typewriter,
Lucida Sans Unicode,
MS Gothic,
MS Mincho,
MS Outlook,
MS PGothic,
MS PMincho,
MS Reference Sans Serif,
MS Reference Specialty,
MS Sans Serif,
MS Serif,
MS UI Gothic,
MT Extra,
MV Boli,
Magneto,
Maiandra GD,
Malgun Gothic,
Mangal,
Marlett,
Matura MT Script Capitals,
Meiryo,
Meiryo UI,
Microsoft Himalaya,
Microsoft JhengHei,
Microsoft New Tai Lue,
Microsoft PhagsPa,
Microsoft Sans Serif,
Microsoft Tai Le,
Microsoft Uighur,
Microsoft YaHei,
Microsoft Yi Baiti,
MingLiU,
MingLiU-ExtB,
MingLiU_HKSCS,
MingLiU_HKSCS-ExtB,
Miriam,
Miriam Fixed,
Mistral,
Modern,
Modern No. 20,
Mongolian Baiti,
Monotype Corsiva,
MoolBoran,
NSimSun,
Narkisim,
Niagara Engraved,
Niagara Solid,
Nyala,
OCR A Extended,
Old English Text MT,
Onyx,
PMingLiU,
PMingLiU-ExtB,
Palace Script MT,
Palatino Linotype,
Papyrus,
Parchment,
Perpetua,
Perpetua Titling MT,
Plantagenet Cherokee,
Playbill,
Poor Richard,
Pristina,
Raavi,
Rage Italic,
Ravie,
Rockwell,
Rockwell Condensed,
Rockwell Extra Bold,
Rod,
Roman,
Sakkal Majalla,
Script,
Script MT Bold,
Segoe Print,
Segoe Script,
Segoe UI,
Segoe UI Light,
Segoe UI Semibold,
Segoe UI Symbol,
Shonar Bangla,
Showcard Gothic,
Shruti,
SimHei,
SimSun,
SimSun-ExtB,
Simplified Arabic,
Simplified Arabic Fixed,
Small Fonts,
Snap ITC,
Stencil,
Sylfaen,
Symbol,
System,
Tahoma,
Tempus Sans ITC,
Terminal,
Times New Roman,
Traditional Arabic,
Trebuchet MS,
Tunga,
Tw Cen MT,
Tw Cen MT Condensed,
Tw Cen MT Condensed Extra Bold,
Utsaah,
Vani,
Verdana,
Vijaya,
Viner Hand ITC,
Vivaldi,
Vladimir Script,
Vrinda,
Webdings,
Wide Latin,
Wingdings,
Wingdings 2,
Wingdings 3
}
*/